version: '3.8'

services:
  mongodb:
    image: mongo:6.0.4
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-vol:/data/db
    networks:
      - mongodb-net

volumes:
  mongodb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\docker\mongodb-vol

networks:
  mongodb-net:
