version: '3.8'

services:
  mongodb:
    image: mongo:6.0.5
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - 27017:27017
    volumes:
      - mongodb-vol:/data/db
    networks:
      - mongodb-net

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-RTM-CU2-ubuntu-20.04
    restart: always
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Passw0rd
      - MSSQL_PID=Express
    ports:
      - 1433:1433
    volumes:
      - mssql-server-vol:/var/opt/mssql/data
    networks:
      - mssql-server-net

volumes:
  mongodb-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\docker\mongodb-vol

  mssql-server-vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: D:\docker\mssql-server-vol

networks:
  mongodb-net:
  mssql-server-net:
